const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const dir=path.join(__dirname,'..'),nodes={};
const c={console,localStorage:{getItem:()=>null,setItem:()=>{}},document:{getElementById:id=>nodes[id]||=( {}),querySelectorAll:()=>[]},setTimeout,clearTimeout,AbortController,fetch:()=>{throw Error('Network should only run on Refresh')}};
vm.createContext(c);for(const f of ['slips.js','bootstrap.js','app.js'])vm.runInContext(fs.readFileSync(path.join(dir,f),'utf8'),c);
const clone=x=>JSON.parse(JSON.stringify(x));
function game(l,final=false,a=10,b=7){return{id:'test',season:{year:2026,type:2},status:{type:{state:final?'post':'in',completed:final,shortDetail:final?'Final':'Q4 2:00'}},competitions:[{competitors:l[1].map((t,i)=>({id:String(i),team:{id:String(i),abbreviation:t},score:String(i?b:a)}))}]}}
function box(p,values){return{boxscore:{players:[{statistics:Object.entries(values).map(([name,stats])=>({name,labels:Object.keys(stats),athletes:[{athlete:{displayName:p},stats:Object.values(stats).map(String)}]}))}]}}}
const all=c.S.flatMap(s=>s.l);
test('renders all 34 legs, all selectors and payouts before fetching',()=>{assert.equal(all.length,34);assert.equal((nodes.app.innerHTML.match(/class="card /g)||[]).length,34);for(const s of c.S)assert.ok(nodes.app.innerHTML.includes(s.p));assert.ok(nodes.app.innerHTML.includes('All 3 Bets'))});
test('every player and game maps exactly to the verified roster/schedule',()=>{for(const l of all){assert.ok(c.ev(c.seed.events,l[1]),l[2]);if(c.playerName(l))assert.ok(c.seed.athletes[c.nm(l[3])],l[2]);assert.equal(c.evalLeg(l,null,c.ev(c.seed.events,l[1]),c.seed.context).s,'pre')}});
test('aliases are exact and suffix-safe, never substring player guesses',()=>{assert.ok(c.matchName('Deebo Samuel Sr.','Deebo Samuel'));assert.ok(c.matchName('Kenneth Walker III','Kenneth Walker'));assert.ok(!c.matchName('Chris Olave','Chris'));assert.equal(c.nt('WSH'),'WAS')});
test('every stat prop supports live, hit and final loss at its actual threshold',()=>{for(const l of all.filter(l=>l[0]==='stat')){const need=Math.ceil(l[6]);let q=box(l[3],{[l[4]]:{[l[5]]:need-1}});assert.equal(c.evalLeg(l,q,game(l),{}).s,'live',l[2]);assert.equal(c.evalLeg(l,q,game(l,true),{}).s,'lost');q=box(l[3],{[l[4]]:{[l[5]]:need}});assert.equal(c.evalLeg(l,q,game(l),{}).s,'hit')}});
test('totals remain live for unders until final; over clears immediately',()=>{let l=all.find(l=>l[0]==='total');assert.equal(c.evalLeg(l,null,game(l,false,20,20),{}).s,'live');assert.equal(c.evalLeg(l,null,game(l,true,20,20),{}).s,'hit');assert.equal(c.evalLeg(l,null,game(l,false,30,30),{}).s,'lost');l=all.find(l=>l[0]==='total'&&l[3]==='over');assert.equal(c.evalLeg(l,null,game(l,false,30,20),{}).s,'hit');assert.equal(c.evalLeg(l,null,game(l,true,20,20),{}).s,'lost')});
test('moneyline and spread wait for final and distinguish integer spread push',()=>{const ml=all.find(l=>l[0]==='ml');assert.equal(c.evalLeg(ml,null,game(ml),{}).s,'live');assert.equal(c.evalLeg(ml,null,game(ml,true),{}).s,'hit');assert.equal(c.evalLeg(ml,null,game(ml,true,7,10),{}).s,'lost');assert.equal(c.evalLeg(ml,null,game(ml,true,10,10),{}).s,'push');const l=all.find(l=>l[0]==='spread'&&l[4]===3);assert.equal(c.evalLeg(l,null,game(l,true,10,13),{}).s,'push');assert.equal(c.evalLeg(l,null,game(l,true,10,12),{}).s,'hit');assert.equal(c.evalLeg(l,null,game(l,true,10,14),{}).s,'lost')});
test('anytime and 2+ TD count scoring, never passing touchdowns',()=>{for(const l of all.filter(l=>l[0]==='td')){const q=box(l[3],{passing:{TD:4},rushing:{TD:0},receiving:{TD:0}});assert.equal(c.evalLeg(l,q,game(l),{}).s,'live');assert.equal(c.evalLeg(l,q,game(l,true),{}).s,'lost');q.boxscore.players[0].statistics[1].athletes[0].stats=[String(l[4])];assert.equal(c.evalLeg(l,q,game(l),{}).s,'hit')}});
test('combined yards include negatives, exact 50+ and strict 47.5 over',()=>{for(const l of all.filter(l=>l[0]==='combo')){const n=Math.ceil(l[4]);const q=box(l[3],{rushing:{YDS:-2},receiving:{YDS:n+2}});assert.equal(c.evalLeg(l,q,game(l),{}).s,'hit');assert.equal(c.evalLeg(l,box(l[3],{rushing:{YDS:0},receiving:{YDS:n-1}}),game(l,true),{}).s,'lost')}});
test('longest rush never substitutes a receiving long',()=>{const l=all.find(l=>l[0]==='longrush'),q=box(l[3],{rushing:{LONG:5},receiving:{LONG:80}});assert.equal(c.evalLeg(l,q,game(l),{}).s,'live');q.boxscore.players[0].statistics[0].athletes[0].stats=['11'];assert.equal(c.evalLeg(l,q,game(l),{}).s,'hit')});
test('Q4 uses drives, deduplicates, ignores other quarters, no plays and tacklers',()=>{const l=all.find(l=>l[0]==='q4rush');let p=(id,quarter,text,yards)=>({id,period:{number:quarter},type:{text:'Rush'},text,statYardage:yards});const plays=[p('a',4,'D.Henry left tackle for 23 yards',23),p('b',4,'D.Henry right tackle for -3 yards',-3),p('c',3,'D.Henry left tackle for 60 yards',60),p('d',4,'D.Henry left tackle for 50 yards. No Play',50),p('e',4,'Other.Player left tackle for 25 yards (D.Henry)',25)];const q={drives:{previous:[{plays}],current:{plays:[plays[0]]}}};assert.equal(c.qRush(q,l[3],4),20);assert.equal(c.evalLeg(l,q,game(l),{}).s,'hit')});
test('sack reads defense and a credited half sack hits FanDuel yes',()=>{const l=all.find(l=>l[0]==='sack'),q=box(l[3],{passing:{SACKS:5},defensive:{SACKS:0.5}});assert.equal(c.evalLeg(l,q,game(l),{}).s,'hit');q.boxscore.players[0].statistics[1].athletes[0].stats=['0'];assert.equal(c.evalLeg(l,q,game(l,true),{}).s,'lost')});
test('D/ST requires a touchdown and matching team, not a return/conversion alone',()=>{const l=all.find(l=>l[0]==='dst');const scoringPlays=[{team:{abbreviation:'PIT'},text:'Interception return for 2 points'},{team:{abbreviation:'CIN'},text:'Punt return TOUCHDOWN'},{team:{abbreviation:'PIT'},text:'Fumble return TOUCHDOWN',scoringType:{points:6}}];assert.equal(c.dst({scoringPlays},'PIT'),1);assert.equal(c.evalLeg(l,{scoringPlays},game(l),{}).s,'hit');assert.equal(c.evalLeg(l,{scoringPlays:[]},game(l,true),{}).s,'lost')});
test('missing summary or missing athlete cannot become a final loss',()=>{for(const l of all.filter(l=>!['ml','spread','total'].includes(l[0]))){assert.equal(c.evalLeg(l,null,game(l,true),{}).s,'pending',l[2]);assert.equal(c.evalLeg(l,{},game(l,true),{}).s,'pending')}});
test('season rows exclude career totals and keep passing sacks separate',()=>{const row=(year,stats)=>({season:{year},stats}),raw={categories:[{name:'passing',names:['gamesPlayed','sacks','interceptions'],statistics:[row(2025,['17','70','20']),row(2026,['2','6','3'])],totals:['19','76','23']},{name:'defensive',names:['gamesPlayed','sacks'],statistics:[row(2026,['2','1'])]},{name:'receiving',names:['gamesPlayed','receptions'],statistics:[row(2026,['2','9'])]}]};const x=c.playerContext(raw);assert.equal(x.gp,2);assert.equal(x.rec,4.5);assert.equal(x.ints,1.5);assert.equal(x.sacks,0.5);assert.equal(c.playerContext({categories:[]}),null)});
test('pregame real season context and no fabricated McMillan average',()=>{assert.equal(c.seed.context.players.derrickhenry.rushY,106);assert.equal(c.seed.context.players.isaiahlikely.rec,6.5);assert.equal(c.seed.context.players.jalenmcmillan,null)});
test('team averages exclude preseason, live games and duplicate events',()=>{const l=all[0],e=game(l,true,24,14),pre=clone(e),live=game(l,false);pre.id='pre';pre.season.type=1;const t=c.teamAverages([e,e,pre,live]);assert.equal(t.BAL.gp,1);assert.equal(t.BAL.ppg,24);assert.equal(t.BAL.margin,10)});
test('refresh failure preserves 34 cards, unlocks buttons, no unhandled rejection',async()=>{await c.go();assert.equal(c.busy,false);assert.equal((nodes.app.innerHTML.match(/class="card /g)||[]).length,34);assert.match(nodes.note.textContent,/unavailable/)});
