var API='https://site.api.espn.com/apis/site/v2/sports/football/nfl',R='20260927-20260928',busy=false;
var S=[{n:'DraftKings',m:'$10.00 → $349.70',l:[
['total',['BAL','DAL'],'Under 59.5','under',59.5],['ml',['PHI','CHI'],'PHI Moneyline','PHI'],['spread',['NE','JAX'],'NE +3','NE',3],['ml',['CIN','PIT'],'CIN Moneyline','CIN'],['ml',['SEA','WAS'],'SEA Moneyline','SEA'],['td',['KC','MIA'],'Kenneth Walker III Anytime TD','Kenneth Walker III',1],['stat',['LV','NO'],'Chris Olave 6+ Receptions','Chris Olave','receiving','REC',6,'REC'],['spread',['LV','NO'],'LV +3.5','LV',3.5]
]},{n:'FanDuel',m:'$2.05 → $272,982.55',l:[
['stat',['NYJ','DET'],'Jameson Williams 80+ Yards','Jameson Williams','receiving','YDS',80,'REC YDS'],['stat',['NYJ','DET'],'Amon-Ra St. Brown 125+ Yards','Amon-Ra St. Brown','receiving','YDS',125,'REC YDS'],['stat',['NYJ','DET'],'Jared Goff 250+ Yards','Jared Goff','passing','YDS',250,'PASS YDS'],['dst',['CIN','PIT'],'Pittsburgh Defense Anytime TD','PIT'],['td',['KC','MIA'],'Emmett Johnson Anytime TD','Emmett Johnson',1],['td',['NE','JAX'],'Chris Rodriguez Jr. Anytime TD','Chris Rodriguez Jr.',1],['stat',['LAC','BUF'],'Justin Herbert Over 0.5 INT','Justin Herbert','passing','INT',1,'INT'],['total',['MIN','TB'],'Over 42.5','over',42.5],['total',['BAL','DAL'],'Under 52.5','under',52.5],['td',['LV','NO'],'Ashton Jeanty 2+ TDs','Ashton Jeanty',2]
]}];
function nt(x){x=(x||'').toUpperCase();if(x==='JAC')return'JAX';if(x==='WSH')return'WAS';return x}function nm(x){return(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(jr|sr|ii|iii|iv)\b/g,'').replace(/[^a-z0-9]/g,'')}function n(v){var m=String(v||0).replace(/,/g,'').match(/-?\d+(\.\d+)?/);return m?+m[0]:0}
function ev(es,g){return es.find(function(e){var a=(e.competitions[0].competitors||[]).map(function(c){return nt(c.team.abbreviation)});return g.every(function(t){return a.indexOf(nt(t))>=0})})}function comp(q,e){return(q&&q.header&&q.header.competitions[0])||e.competitions[0]}function score(c,t){var x=(c.competitors||[]).find(function(z){return nt(z.team.abbreviation)===nt(t)});return x?n(x.score):0}function st(q,e){var c=comp(q,e),s=c.status||e.status||{};return{v:(s.type&&s.type.state)||'pre',d:(s.type&&(s.type.shortDetail||s.type.detail))||'Scheduled'}}
function poss(q){var c=q&&q.header&&q.header.competitions[0],id=c&&c.situation&&c.situation.possession,p=c&&(c.competitors||[]).find(function(x){return String(x.id||x.team.id)===String(id)||x.possession===true});if(p)return nt(p.team.abbreviation);return q&&q.drives&&q.drives.current&&q.drives.current.team?nt(q.drives.current.team.abbreviation):''}
function ps(q,p,cat,lab){var out=0;(q&&q.boxscore&&q.boxscore.players||[]).forEach(function(tm){(tm.statistics||[]).forEach(function(g){if((g.name||'').toLowerCase()!==cat.toLowerCase())return;var i=(g.labels||[]).findIndex(function(x){return String(x).toUpperCase()===lab});if(i<0)return;(g.athletes||[]).forEach(function(a){if(nm(a.athlete.displayName).indexOf(nm(p))>=0||nm(p).indexOf(nm(a.athlete.displayName))>=0)out=n(a.stats[i])})})});return out}
function td(q,p){var z=0;(q&&q.boxscore&&q.boxscore.players||[]).forEach(function(tm){(tm.statistics||[]).forEach(function(g){if((g.name||'').toLowerCase()==='passing')return;var i=(g.labels||[]).findIndex(function(x){return String(x).toUpperCase()==='TD'});if(i<0)return;(g.athletes||[]).forEach(function(a){if(nm(a.athlete.displayName).indexOf(nm(p))>=0||nm(p).indexOf(nm(a.athlete.displayName))>=0)z+=n(a.stats[i])})})});return z}
function dst(q,t){var z=0,re=/(interception.*return|fumble.*return|punt.*return|kickoff.*return|blocked.*(return|end zone)|defensive touchdown|special teams touchdown)/i;(q&&q.scoringPlays||[]).forEach(function(p){var a=nt(p.team&&p.team.abbreviation),x=[p.text,p.shortText,p.type&&p.type.text].filter(Boolean).join(' ');if(a===nt(t)&&re.test(x))z++});return z}
function evalLeg(l,q,e){if(!e)return{x:l,s:'lost',v:'—',d:'Game not found',g:'Unavailable'};var c=comp(q,e),a=score(c,l[1][0]),b=score(c,l[1][1]),gs=st(q,e),live=gs.v==='in',fin=gs.v==='post',s=live?'live':(fin?'final':'pre'),v='',d='',x=0,y=0;
 if(l[0]==='total'){x=a+b;v=x+' / '+l[4];if(l[3]==='over'){if(x>l[4]){s='hit';d='Over cleared.'}else if(fin){s='lost';d='Finished short.'}else d='Needs '+(Math.floor(l[4]-x)+1)+' more total points.'}else{if(x>l[4]){s='lost';d='Under can no longer hit.'}else if(fin){s='hit';d='Final stayed under.'}else d=(l[4]-x).toFixed(1)+' points below the line.'}}
 if(l[0]==='ml'){x=l[3]===l[1][0]?a:b;y=l[3]===l[1][0]?b:a;v=l[3]+' '+x+' — '+y;if(fin){s=x>y?'hit':'lost';d=s==='hit'?'Moneyline won.':'Moneyline lost.'}else d=x>y?'Currently leading by '+(x-y)+'.':x<y?'Currently trailing by '+(y-x)+'.':'Game tied.'}
 if(l[0]==='spread'){x=l[3]===l[1][0]?a:b;y=l[3]===l[1][0]?b:a;var cv=x+l[4]-y;v=l[3]+' +'+l[4];if(fin){s=cv>0?'hit':cv===0?'push':'lost';d=cv>0?'Covered by '+cv.toFixed(1)+'.':cv===0?'Push.':'Missed cover by '+Math.abs(cv).toFixed(1)+'.'}else d=cv>0?'Currently covering by '+cv.toFixed(1)+'.':cv===0?'Currently a push.':'Outside cover by '+Math.abs(cv).toFixed(1)+'.'}
 if(l[0]==='stat'){x=ps(q,l[3],l[4],l[5]);v=x+' / '+l[6]+' '+l[7];if(x>=l[6]){s='hit';d='Target reached.'}else if(fin){s='lost';d='Finished '+(l[6]-x)+' short.'}else d='Needs '+(l[6]-x)+' more.'}
 if(l[0]==='td'){x=td(q,l[3]);v=x+' / '+l[4]+' TD';if(x>=l[4]){s='hit';d='Touchdown target reached.'}else if(fin){s='lost';d='Finished with '+x+' TD.'}else d='Needs '+(l[4]-x)+' touchdown'+(l[4]-x===1?'':'s')+'.'}
 if(l[0]==='dst'){x=dst(q,l[3]);v=x+' / 1 D/ST TD';if(x){s='hit';d='D/ST touchdown detected.'}else if(fin){s='lost';d='No D/ST touchdown.'}else d='Needs a defensive/special-teams TD.'}
 var p=poss(q),info=l[1][0]+' '+a+' — '+l[1][1]+' '+b+' · '+(fin?'Final':gs.d)+(live&&p?' · 🏈 '+p:'');return{x:l,s:s,v:v,d:d,g:info}}
function card(o){return'<div class="card '+(o.s==='final'?'':o.s)+'"><div class="r"><div><div class="pick">'+o.x[2]+'</div><div class="game">'+o.x[1].join(' @ ')+'</div></div><span class="badge">'+(o.s==='pre'?'UPCOMING':o.s.toUpperCase())+'</span></div><div class="metric">'+o.v+'</div><div class="detail">'+o.d+'</div><div class="state">'+o.g+'</div></div>'}
function render(data){var h='';data.forEach(function(s){var hit=s.a.filter(function(x){return x.s==='hit'}).length,live=s.a.filter(function(x){return x.s==='live'}).length,lost=s.a.filter(function(x){return x.s==='lost'}).length,up=s.a.filter(function(x){return x.s==='pre'}).length;s.a.sort(function(a,b){var p={live:0,hit:1,pre:3,final:4,lost:5};return(p[a.s]||2)-(p[b.s]||2)});h+='<section class="book"><div class="bh"><div class="bn">'+s.n+'</div><div class="money">'+s.m+'</div></div><div class="sum"><span><b>'+hit+'</b>Hit</span><span><b>'+live+'</b>Live</span><span><b>'+lost+'</b>Lost</span><span><b>'+up+'</b>Upcoming</span></div>'+s.a.map(card).join('')+'</section>'});document.getElementById('app').innerHTML=h}
async function fj(u){var r=await fetch(u+(u.indexOf('?')>=0?'&':'?')+'_='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()}async function go(){if(busy)return;busy=true;document.getElementById('big').textContent='Refreshing…';document.getElementById('last').textContent='Fetching ESPN…';try{var b=await fj(API+'/scoreboard?limit=100&dates='+R),es=b.events||[],ids={};S.forEach(function(s){s.l.forEach(function(l){var e=ev(es,l[1]);if(e)ids[e.id]=e})});var qs={};await Promise.all(Object.keys(ids).map(async function(id){try{qs[id]=await fj(API+'/summary?event='+id)}catch(e){qs[id]=null}}));var data=S.map(function(s){return{n:s.n,m:s.m,a:s.l.map(function(l){var e=ev(es,l[1]);return evalLeg(l,e&&qs[e.id],e)})}});render(data);document.getElementById('last').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'});document.getElementById('note').innerHTML='<b>Fresh snapshot loaded.</b> Tap Refresh again whenever you want a new one.'}catch(e){document.getElementById('last').textContent='Refresh failed';document.getElementById('note').innerHTML='<span class="err"><b>Could not reach ESPN.</b> Check service and tap Refresh again.</span>'}busy=false;document.getElementById('big').textContent='↻ Refresh BetPulse'}go();